-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 07:41:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TORNEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TORNEO` (
  `año` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `lugar` VARCHAR(45) NULL,
  `formato` VARCHAR(45) NULL,
  PRIMARY KEY (`año`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAMPEÓN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAMPEÓN` (
  `idCAMPEÓN` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `pasiva` VARCHAR(45) NULL,
  `habilidad1` VARCHAR(45) NULL,
  `habilidad2` VARCHAR(45) NULL,
  `habilidad3` VARCHAR(45) NULL,
  `habilidad4` VARCHAR(45) NULL,
  PRIMARY KEY (`idCAMPEÓN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPO` (
  `idEQUIPO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `región` VARCHAR(45) NULL,
  `fecha_fundación` DATE NULL,
  PRIMARY KEY (`idEQUIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARTIDO` (
  `idPARTIDO` INT NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `resultado_equipo_azul` INT NULL,
  `resultado_equipo_rojo` INT NULL,
  `cantidad_juegos` ENUM('BO1', 'BO3', 'BO5') NULL,
  `TORNEO_año` INT NOT NULL,
  `EQUIPO_idEQUIPO_rojo` INT NOT NULL,
  `EQUIPO_idEQUIPO_azul` INT NOT NULL,
  PRIMARY KEY (`idPARTIDO`),
  INDEX `fk_PARTIDO_TORNEO1_idx` (`TORNEO_año` ASC) VISIBLE,
  INDEX `fk_PARTIDO_EQUIPO1_idx` (`EQUIPO_idEQUIPO_rojo` ASC) VISIBLE,
  INDEX `fk_PARTIDO_EQUIPO2_idx` (`EQUIPO_idEQUIPO_azul` ASC) VISIBLE,
  CONSTRAINT `fk_PARTIDO_TORNEO1`
    FOREIGN KEY (`TORNEO_año`)
    REFERENCES `mydb`.`TORNEO` (`año`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDO_EQUIPO1`
    FOREIGN KEY (`EQUIPO_idEQUIPO_rojo`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDO_EQUIPO2`
    FOREIGN KEY (`EQUIPO_idEQUIPO_azul`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RANKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RANKING` (
  `posición` INT NULL,
  `puntos totales` INT NULL,
  `número_victorias` INT NULL,
  `número_derrotas` INT NULL,
  `número_empates` INT NULL,
  `EQUIPO_idEQUIPO` INT NOT NULL,
  PRIMARY KEY (`EQUIPO_idEQUIPO`),
  CONSTRAINT `fk_RANKING_EQUIPO`
    FOREIGN KEY (`EQUIPO_idEQUIPO`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JUGADOR` (
  `idJUGADOR` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `rol` ENUM('top', 'jgl', 'mid', 'adc', 'supp') NULL,
  `EQUIPO_idEQUIPO` INT NOT NULL,
  PRIMARY KEY (`idJUGADOR`),
  INDEX `fk_JUGADOR_EQUIPO1_idx` (`EQUIPO_idEQUIPO` ASC) VISIBLE,
  CONSTRAINT `fk_JUGADOR_EQUIPO1`
    FOREIGN KEY (`EQUIPO_idEQUIPO`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RONDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RONDA` (
  `número_ronda` INT NOT NULL,
  `duración` FLOAT NULL,
  `PARTIDO_idPARTIDO` INT NOT NULL,
  `EQUIPO_idEQUIPO_ganador` INT NOT NULL,
  PRIMARY KEY (`PARTIDO_idPARTIDO`, `número_ronda`),
  INDEX `fk_RONDA_EQUIPO1_idx` (`EQUIPO_idEQUIPO_ganador` ASC) VISIBLE,
  CONSTRAINT `fk_RONDA_PARTIDO1`
    FOREIGN KEY (`PARTIDO_idPARTIDO`)
    REFERENCES `mydb`.`PARTIDO` (`idPARTIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RONDA_EQUIPO1`
    FOREIGN KEY (`EQUIPO_idEQUIPO_ganador`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RONDA_has_CAMPEÓN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RONDA_has_CAMPEÓN` (
  `RONDA_PARTIDO_idPARTIDO` INT NOT NULL,
  `RONDA_número_ronda` INT NOT NULL,
  `CAMPEÓN_idCAMPEÓN` INT NOT NULL,
  `tipo` ENUM('pick', 'ban') NULL,
  `color_equipo` ENUM('rojo', 'azul') NULL,
  PRIMARY KEY (`RONDA_PARTIDO_idPARTIDO`, `RONDA_número_ronda`, `CAMPEÓN_idCAMPEÓN`),
  INDEX `fk_RONDA_has_CAMPEÓN_CAMPEÓN1_idx` (`CAMPEÓN_idCAMPEÓN` ASC) VISIBLE,
  INDEX `fk_RONDA_has_CAMPEÓN_RONDA1_idx` (`RONDA_PARTIDO_idPARTIDO` ASC, `RONDA_número_ronda` ASC) VISIBLE,
  CONSTRAINT `fk_RONDA_has_CAMPEÓN_RONDA1`
    FOREIGN KEY (`RONDA_PARTIDO_idPARTIDO` , `RONDA_número_ronda`)
    REFERENCES `mydb`.`RONDA` (`PARTIDO_idPARTIDO` , `número_ronda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RONDA_has_CAMPEÓN_CAMPEÓN1`
    FOREIGN KEY (`CAMPEÓN_idCAMPEÓN`)
    REFERENCES `mydb`.`CAMPEÓN` (`idCAMPEÓN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPO_has_JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPO_has_JUGADOR` (
  `EQUIPO_idEQUIPO` INT NOT NULL,
  `JUGADOR_idJUGADOR` INT NOT NULL,
  PRIMARY KEY (`EQUIPO_idEQUIPO`, `JUGADOR_idJUGADOR`),
  INDEX `fk_EQUIPO_has_JUGADOR_JUGADOR1_idx` (`JUGADOR_idJUGADOR` ASC) VISIBLE,
  INDEX `fk_EQUIPO_has_JUGADOR_EQUIPO1_idx` (`EQUIPO_idEQUIPO` ASC) VISIBLE,
  CONSTRAINT `fk_EQUIPO_has_JUGADOR_EQUIPO1`
    FOREIGN KEY (`EQUIPO_idEQUIPO`)
    REFERENCES `mydb`.`EQUIPO` (`idEQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPO_has_JUGADOR_JUGADOR1`
    FOREIGN KEY (`JUGADOR_idJUGADOR`)
    REFERENCES `mydb`.`JUGADOR` (`idJUGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
